version: "3.9"

services:
  mysql:
    extends:
      file: docker-compose.infra.yml
      service: mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"

  redis:
    extends:
      file: docker-compose.infra.yml
      service: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"

  nginx:
    image: nginx:1.27
    container_name: scspace-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ../nginx/nginx.local.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - scspace-internal-network

networks:
  scspace-internal-network:
    external: true
    name: scspace-internal-network
  scspace-infra-network:
    external: true
    name: scspace-infra-network

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
